# Generated by Django 3.0.6 on 2020-05-29 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакты', 'verbose_name_plural': 'Контакты'},
        ),
    ]
