# Generated by Django 3.0.6 on 2020-05-17 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieshots',
            old_name='movies',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='movies',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='movies',
            new_name='movie',
        ),
    ]
